package junos

// rpcCommand lists the commands that will be called.
var rpcCommand = map[string]string{
	"command":                          "<rpc><command format=\"text\">%s</command></rpc>",
	"command-xml":                      "<rpc><command format=\"xml\">%s</command></rpc>",
	"commit":                           "<rpc><commit-configuration/></rpc>",
	"commit-at":                        "<rpc><commit-configuration><at-time>%s</at-time></commit-configuration></rpc>",
	"commit-check":                     "<rpc><commit-configuration><check/></commit-configuration></rpc>",
	"commit-confirm":                   "<rpc><commit-configuration><confirmed/><confirm-timeout>%d</confirm-timeout></commit-configuration></rpc>",
	"facts-re":                         "<rpc><get-route-engine-information/></rpc>",
	"facts-chassis":                    "<rpc><get-chassis-inventory/></rpc>",
	"config-file-set":                  "<rpc><load-configuration action=\"set\" format=\"text\"><configuration-set>%s</configuration-set></load-configuration></rpc>",
	"config-file-text":                 "<rpc><load-configuration format=\"text\"><configuration-text>%s</configuration-text></load-configuration></rpc>",
	"config-file-xml":                  "<rpc><load-configuration format=\"xml\"><configuration>%s</configuration></load-configuration></rpc>",
	"config-url-set":                   "<rpc><load-configuration action=\"set\" format=\"text\" url=\"%s\"/></rpc>",
	"config-url-text":                  "<rpc><load-configuration format=\"text\" url=\"%s\"/></rpc>",
	"config-url-xml":                   "<rpc><load-configuration format=\"xml\" url=\"%s\"/></rpc>",
	"get-rescue-information":           "<rpc><get-rescue-information><format>text</format></get-rescue-information></rpc>",
	"get-rollback-information":         "<rpc><get-rollback-information><rollback>%d</rollback><format>text</format></get-rollback-information></rpc>",
	"get-rollback-information-compare": "<rpc><get-rollback-information><rollback>0</rollback><compare>%d</compare><format>text</format></get-rollback-information></rpc>",
	"hardware":                         "<rpc><get-chassis-inventory/></rpc>",
	"lock":                             "<rpc><lock><target><candidate/></target></lock></rpc>",
	"rescue-config":                    "<rpc><load-configuration rescue=\"rescue\"/></rpc>",
	"rescue-delete":                    "<rpc><request-delete-rescue-configuration/></rpc>",
	"rescue-save":                      "<rpc><request-save-rescue-configuration/></rpc>",
	"rollback-config":                  "<rpc><load-configuration rollback=\"%d\"/></rpc>",
	"route":                            "<rpc><get-route-engine-information/></rpc>",
	"software":                         "<rpc><get-software-information/></rpc>",
	"unlock":                           "<rpc><unlock><target><candidate/></target></unlock></rpc>",
	"version":                          "<rpc><get-software-information/></rpc>",
}
